services:
  rpa_solicitudes:
    image: web_corredor
    #container_name: webhookCorredor
    build: .
    volumes:
      - ./Codigo:/app/Codigo
      - ${HOST_DOWNLOADS_PATH:-./Downloads}:/app/Downloads
    restart: always
    #command: supervisord -c /etc/supervisord.conf

# Comando: docker build --no-cache -t web_corredor .
