services:
  webCorredor:
    image: web_corredor
    build: .
    volumes:
      - ./Codigo:/app/Codigo

# Comando: docker build --no-cache -t web_corredor .
# Comando: docker compose build
# Comando para crear una imagen base : docker build -f Dockerfile.base -t rpa-base:chrome145 .